PACKAGE_NAME="gxfp"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="gxfp"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"
AUTOINSTALL="yes"
MAKE[0]="make KERNELDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
